[workspace]
resolver = "3"

members = ["imgcp", "imgcp_lib", "imgcp_gui"]

[workspace.dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
ffmpeg-next = "7"
flexi_logger = "0.30"
imgcp_lib = { path = "imgcp_lib" }
log = "0.4"
promptly = "0.3"
rexif = "0.7"
rfd = "0.15"
same-file = "1"
sha-1 = "0.10"
thiserror = "2"
walkdir = "2"
