name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    container: jrottenberg/ffmpeg:6.1-ubuntu

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
          apt update
          apt install -y --no-install-recommends clang curl pkg-config
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy          
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Lint
      run: |
          cargo clippy --features $FEATURES -- -D warnings
    - name: Check format
      run: |
          cargo fmt -- --check      
